"""allow_null_is_answer_correct_in_reviews

Revision ID: 589f93d393cd
Revises: 4235fd04f6f1
Create Date: 2025-12-31 14:16:37.213513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589f93d393cd'
down_revision = '4235fd04f6f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'is_answer_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_reviews_task_id'), 'reviews', ['task_id'], unique=False)
    op.create_index(op.f('ix_validation_records_validated_problem_id'), 'validation_records', ['validated_problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_records_validated_problem_id'), table_name='validation_records')
    op.drop_index(op.f('ix_reviews_task_id'), table_name='reviews')
    op.alter_column('reviews', 'is_answer_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###

