"""add validated problem export table

Revision ID: validated_export_001
Revises: add_mongo_id_001
Create Date: 2024-12-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'validated_export_001'
down_revision = 'add_mongo_id_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 检查表是否已存在
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_name='validated_problem_exports'
    """))
    
    if result.fetchone():
        # 表已存在，跳过创建
        return
    
    # 使用已存在的materialcategory枚举类型，不创建新的
    materialcategory_enum = postgresql.ENUM(
        'high_school_comprehensive', 'college_comprehensive', 'high_school_algebra', 
        'high_school_geometry', 'high_school_number_theory', 'high_school_combinatorics', 
        'college_algebra', 'college_number_theory', 'college_analysis', 'college_combinatorics', 
        'college_geometry', 'college_optimization', 
        name='materialcategory', 
        create_type=False
    )
    
    op.create_table('validated_problem_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('category', materialcategory_enum, nullable=False),
    sa.Column('difficulty_validation', sa.JSON(), nullable=True),
    sa.Column('originality_check', sa.JSON(), nullable=False),
    sa.Column('rigor_check', sa.JSON(), nullable=False),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validated_problem_exports_created_at'), 'validated_problem_exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_validated_problem_exports_id'), 'validated_problem_exports', ['id'], unique=False)
    op.create_index(op.f('ix_validated_problem_exports_user_id'), 'validated_problem_exports', ['user_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validated_problem_exports_user_id'), table_name='validated_problem_exports')
    op.drop_index(op.f('ix_validated_problem_exports_id'), table_name='validated_problem_exports')
    op.drop_index(op.f('ix_validated_problem_exports_created_at'), table_name='validated_problem_exports')
    op.drop_table('validated_problem_exports')
    # ### end Alembic commands ###

