"""add_admin_review_fields_to_validated_problem_exports

Revision ID: cc6e11dc09bf
Revises: 19e6d290d3e9
Create Date: 2025-12-29 18:05:26.044957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6e11dc09bf'
down_revision = '19e6d290d3e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reviews_validated_export_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_validated_problem_id'), 'reviews', ['validated_problem_id'], unique=False)
    op.drop_index(op.f('idx_tasks_validated_export_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_validated_problem_id'), 'tasks', ['validated_problem_id'], unique=False)
    
    # 先创建枚举类型
    adminreviewstatus = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='adminreviewstatus')
    adminreviewstatus.create(op.get_bind(), checkfirst=True)
    
    # 添加字段，初始允许NULL
    op.add_column('validated_problem_exports', sa.Column('admin_review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='adminreviewstatus'), nullable=True))
    op.add_column('validated_problem_exports', sa.Column('admin_reviewer_id', sa.Integer(), nullable=True))
    op.add_column('validated_problem_exports', sa.Column('admin_review_note', sa.Text(), nullable=True))
    op.add_column('validated_problem_exports', sa.Column('admin_reviewed_at', sa.DateTime(), nullable=True))
    
    # 为所有现有记录设置默认值为PENDING
    op.execute("UPDATE validated_problem_exports SET admin_review_status = 'PENDING' WHERE admin_review_status IS NULL")
    
    # 现在将字段设置为NOT NULL
    op.alter_column('validated_problem_exports', 'admin_review_status', nullable=False)
    
    op.create_index(op.f('ix_validated_problem_exports_admin_review_status'), 'validated_problem_exports', ['admin_review_status'], unique=False)
    op.create_foreign_key(None, 'validated_problem_exports', 'users', ['admin_reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validated_problem_exports', type_='foreignkey')
    op.drop_index(op.f('ix_validated_problem_exports_admin_review_status'), table_name='validated_problem_exports')
    op.drop_column('validated_problem_exports', 'admin_reviewed_at')
    op.drop_column('validated_problem_exports', 'admin_review_note')
    op.drop_column('validated_problem_exports', 'admin_reviewer_id')
    op.drop_column('validated_problem_exports', 'admin_review_status')
    op.drop_index(op.f('ix_tasks_validated_problem_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_validated_export_id'), 'tasks', ['validated_problem_id'], unique=False)
    op.drop_index(op.f('ix_reviews_validated_problem_id'), table_name='reviews')
    op.create_index(op.f('idx_reviews_validated_export_id'), 'reviews', ['validated_problem_id'], unique=False)
    # ### end Alembic commands ###

